### ISSUE TITLE
IOTA transaction spammer does not work

### ISSUE THREAD

**Issue by Iotacus** [pRizz/iota.transactionSpammer.js#6]
The IOTA transaction spammer at https://prizz.github.io/iota-transaction-spammer-webapp/ never works for me. No confirmations, no transactions added to the tangle. Please see the enclosed screenshot. My computer uses Intel HD graphics 630 (Intel Core i3-7350K). If a computer uses Intel HD graphics, Curl Implementation should be set to "CCurl implementation" in the IOTA wallet. Otherwise addresses cannot be attached to the tangle and the error message "invalid transaction hash" is displayed. Maybe the issue with the transaction spammer is due to the same reason.

A screenshot of the transaction spammer:
![spammer](https://user-images.githubusercontent.com/33297789/32299611-e1e72a0a-bf5e-11e7-9256-5653a06be5e3.png)

The event log of the transaction spammer:
[Event_log.txt](https://github.com/pRizz/iota.transactionSpammer.js/files/1435811/Event_log.txt)

**Comment by z3rone** [comment]
The problem seems to be, that you can access the example on github only via HTTPS and there is only one provider in the httpsProviders array ("https://iotanode.prizziota.com:443"). If you add more (working) nodes to the array the example works fine...

Could you add more HTTPS nodes to the example? @pRizz

**Comment by pRizz** [comment]
This should be fixed if run properly
